import type { Profile } from "../../../src/schemas/profile.js";
import type { Node } from "../../../src/schemas/node.js";

export function emptyProfile(overrides: Partial<Profile> = {}): Profile {
  return {
    id: "matrix",
    name: "Matrix",
    token: "matrixtoken",
    providers: [],
    node_filter: { rename_rules: [], exclude_types: [], sort_by_region: false },
    chain_rules: [],
    proxy_groups: [],
    rule_modules: [],
    surge_modules: [],
    userinfo: { enabled: false, mode: "sum", expose_per_provider_headers: true },
    managed_config_url: "auto",
    managed_config_interval: 86400,
    managed_config_strict: false,
    clash_options: { use_proxy_providers: false, flag: "mihomo", group_style: "flow" },
    ...overrides,
  };
}

/**
 * 每个协议一份最小化的节点 fixture,字段尽量多覆盖,便于 generator 字段映射回归。
 * 测试以 toMatchSnapshot 的形式比对,refactor 字段映射后用 `vitest -u` 更新。
 */
export const protocolFixtures: { name: string; node: Node }[] = [
  {
    name: "ss-2022",
    node: {
      name: "🇯🇵 JP-SS",
      type: "ss",
      server: "ss.example.com",
      port: 8388,
      cipher: "2022-blake3-aes-128-gcm",
      password: "Pwd@Strong",
      udp: true,
      mptcp: true,
      tags: [],
    },
  },
  {
    name: "vmess-ws",
    node: {
      name: "🇸🇬 SG-VMess-WS",
      type: "vmess",
      server: "sg.example.com",
      port: 443,
      uuid: "11111111-2222-3333-4444-555555555555",
      alter_id: 0,
      cipher: "auto",
      tls: true,
      sni: "sg.example.com",
      network: "ws",
      ws_opts: { path: "/vm", headers: { Host: "sg.example.com" } },
      udp: true,
      tags: [],
    },
  },
  {
    name: "vless-reality",
    node: {
      name: "🇺🇸 US-Reality",
      type: "vless",
      server: "us.example.com",
      port: 443,
      uuid: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
      flow: "xtls-rprx-vision",
      tls: true,
      sni: "www.cloudflare.com",
      client_fingerprint: "chrome",
      reality_opts: { public_key: "REAL_PUB_KEY", short_id: "abcd1234" },
      network: "tcp",
      udp: true,
      tags: [],
    },
  },
  {
    name: "trojan-ws",
    node: {
      name: "🇭🇰 HK-Trojan",
      type: "trojan",
      server: "hk.example.com",
      port: 443,
      password: "trojan-pass,with,commas",
      tls: true,
      sni: "hk.cdn.example.com",
      network: "ws",
      ws_opts: { path: "/tj", headers: { Host: "hk.cdn.example.com" } },
      udp: true,
      tags: [],
    },
  },
  {
    name: "hysteria2",
    node: {
      name: "🇩🇪 DE-Hy2",
      type: "hysteria2",
      server: "de.example.com",
      port: 36000,
      password: "hy2-pwd",
      up: "200 Mbps",
      down: "500 Mbps",
      obfs: "salamander",
      obfs_password: "obfsx",
      port_hopping: "36000-36100",
      hop_interval: 30,
      tls: true,
      alpn: ["h3"],
      udp: true,
      tags: [],
    },
  },
  {
    name: "hysteria2-gecko",
    node: {
      name: "🇩🇪 DE-Hy2-Gecko",
      type: "hysteria2",
      server: "de2.example.com",
      port: 36443,
      password: "hy2-gecko-pwd",
      down: "300 Mbps",
      obfs: "gecko",
      obfs_password: "gecko-obfs-pwd",
      tls: true,
      udp: true,
      tags: [],
    },
  },
  {
    name: "tuic-v5",
    node: {
      name: "🇰🇷 KR-TUIC",
      type: "tuic",
      server: "kr.example.com",
      port: 1024,
      uuid: "12341234-1234-1234-1234-123412341234",
      password: "tuic-pwd",
      tuic_version: 5,
      congestion_controller: "bbr",
      tls: true,
      sni: "kr.example.com",
      alpn: ["h3"],
      udp: true,
      tags: [],
    },
  },
  {
    name: "wireguard",
    node: {
      name: "🛡 WARP",
      type: "wireguard",
      server: "engage.cloudflareclient.com",
      port: 2408,
      private_key: "PRIVATE_KEY_BASE64",
      public_key: "PUBLIC_KEY_BASE64",
      preshared_key: "PSK_BASE64",
      ip: "172.16.0.2/32",
      ipv6: "2606:4700:110:8caf:5d6f:f0ec:7e2b:33d7/128",
      reserved: "AAAA",
      mtu: 1280,
      udp: true,
      tags: [],
    },
  },
  {
    name: "snell",
    node: {
      name: "🇹🇼 TW-Snell",
      type: "snell",
      server: "tw.example.com",
      port: 443,
      psk: "snell-psk",
      snell_version: 4,
      obfs: "http",
      obfs_host: "tw.example.com",
      udp: true,
      tags: [],
    },
  },
  {
    // 机场常见形态:伪装 SNI(ixigua.com)+ 服务器证书 SHA256 锁定。
    // 验证 fingerprint -> clash `fingerprint:` / surge `server-cert-fingerprint-sha256=`。
    // reuse=false: AnyTLS 规范默认开启连接复用,显式关闭仅 Surge 端有键(mihomo 无对应)。
    name: "anytls-cert-pinning",
    node: {
      name: "🇭🇰 HK-AnyTLS",
      type: "anytls",
      server: "8d4a2926.example.com",
      port: 15026,
      password: "anytls-pwd",
      reuse: false,
      tls: true,
      sni: "ixigua.com",
      fingerprint: "fac26f65c034829da42d740d23c4a7202475a3834f0ebaecae5f934adbbfd640",
      tfo: true,
      udp: true,
      tags: [],
    },
  },
  {
    // Shadow TLS 混淆叠加在 ss 上:
    // clash → plugin: shadow-tls + plugin-opts { password, host, version }
    // surge → shadow-tls-password= / shadow-tls-sni= / shadow-tls-version=
    name: "ss-shadow-tls",
    node: {
      name: "🇭🇰 HK-SS-STLS",
      type: "ss",
      server: "stls.example.com",
      port: 443,
      cipher: "2022-blake3-aes-128-gcm",
      password: "ss-pwd",
      shadow_tls_password: "stls-pwd",
      shadow_tls_sni: "cloud.tencent.com",
      shadow_tls_version: 3,
      udp: true,
      tags: [],
    },
  },
  {
    // Snell v6(iOS 5.20.0+/Mac 6.7.0+ beta)+ 连接复用;Clash 端整节点跳过 + warning。
    name: "snell-v6",
    node: {
      name: "🇹🇼 TW-Snell-v6",
      type: "snell",
      server: "tw6.example.com",
      port: 7177,
      psk: "snell6-psk",
      snell_version: 6,
      reuse: true,
      udp: true,
      tags: [],
    },
  },
];
